export const FETCH_COIN_DATA = 'FETCH_COIN_DATA';
export const FETCH_COIN_DATA_SUCCESS = 'FETCH_COIN_DATA_SUCCESS';
export const FETCH_COIN_DATA_FAIL = 'FETCH_COIN_DATA_FAIL';
export const FETCH_GLOBAL_DATA = 'FETCH_GLOBAL_DATA';
export const FETCH_GLOBAL_DATA_SUCCESS = 'FETCH_GLOBAL_DATA_SUCCESS';
export const FETCH_GLOBAL_DATA_FAIL = 'FETCH_GLOBAL_DATA_FAIL';
